### ISSUE TITLE
After drag and drop colors always visible

### ISSUE THREAD

**Issue by lifehaschanged** [Quorafind/Outliner-View#11]
I tested it again and drag and drop is working correctly, sorry about the confusion.
I will change this request to a possible bug report:
When lines are drag and dropped, the background color of the dragged and drop lines will be visible even when the mouse is released:
<img width="297" alt="2024-05-08 17_25_17-outliner-20240508172126 - Obsidian Sandbox - Obsidian v1 5 12" src="https://github.com/Quorafind/Outliner-View/assets/81463128/3fe77e52-f69d-409d-9841-87ed5e846713">

**Comment by Quorafind** [comment]
Fixed
