### ISSUE TITLE
块嵌入和非嵌入内容的区分问题

### ISSUE THREAD

**Issue by zqz365001** [Quorafind/Outliner-View#12]
想提一提想法，能否把 嵌入的和非嵌入的，在编辑状态中的浏览时，就能区分开呢？通过颜色或者 标识 体现出来

![fa83d0bf17d4630d085755957853739](https://github.com/Quorafind/Outliner-View/assets/27180737/12629626-ce29-48d6-97fb-29daab6350e5)

![image](https://github.com/Quorafind/Outliner-View/assets/27180737/ea5cacb3-8af3-43ec-b132-bfbf1a0d46be)

![1037c007ec43fd29eadb2346071df45](https://github.com/Quorafind/Outliner-View/assets/27180737/794c40ac-aa1c-41ab-ac11-29ec9774a57e)
上图是 原来的 块嵌入，带 小锁的标识，很快能区分开是否是嵌入的内容。
中图是 非块嵌入的内容
下图是现在的块嵌入编辑，和非嵌入的内容在编辑状态浏览时有些区分不开了

**Comment by Quorafind** [comment]
重复 #6
