### ISSUE TITLE
BUG: Clicking link will enter edit mode

### ISSUE THREAD

**Issue by Friedolito** [Quorafind/Outliner-View#2]
First off: THANK YOU!! Inline editing is a dream come true I had for a long time.

Problem: 
Clicking on links, that are not an embed will go into an edit mode and I'm not able to follow the link.

![Screenshot -2024-05-07 at 10 09 38](https://github.com/Quorafind/Outliner-View/assets/53973194/45d21f22-d40a-4581-a073-215e3824e533)

Disabling plug-in and restarting obsmd will restore normal behavior, clicking on link follows the link. 

Obsmd: v1.5.12
Outliner View: Version: 0.0.9

Happy to give further infos if needed.

**Comment by Quorafind** [comment]
It is a bug. And would be fixed soon.

**Comment by Quorafind** [comment]
Should be fixed in 0.0.10

**Comment by Friedolito** [comment]
Nice! Thanks!
