### ISSUE TITLE
Keep the jump back button for the Embedded content

### ISSUE THREAD

**Issue by wwjCMP** [Quorafind/Outliner-View#6]
现在嵌入块可以直接编辑，但在使用预览模式下没有了跳转回原文的按钮，也不好区分嵌入的内容。在阅读模式下有跳转按钮。

希望保留跳转按钮，或增加一个开关选项。

**Comment by Quorafind** [comment]
已修复

**Comment by wwjCMP** [comment]
![image](https://github.com/Quorafind/Outliner-View/assets/32979859/8b62ce86-81d4-4cbd-b48a-11554f34e203)
嵌入块右侧会有这样的细线，非常难受

**Comment by Quorafind** [comment]
不喜欢的话，自己用css去除：

```
.internal-embed.is-loaded:not(.embedded-part):has(.markdown-source-view):before {
   content: unset;
}
```
